name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install ruff mypy pytest
      - name: Run ruff
        run: ruff .
      - name: Run mypy
        run: mypy . || true
      - name: Run tests
        run: pytest -q || true
